name: coveralls

on: push

jobs:
  test:
    name: Coveralls Upload
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: 1.1.16

    - name: Install dependencies
      run: bun install

    - name: Run JavaScript/TypeScript tests
      run: bun run test

    - name: Upload coverage to Coveralls
      run: |
        if [ -f ./coverage/lcov.info ]; then
          bun run coveralls < ./coverage/lcov.info
        fi
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
