name: test-workflow

on: push

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: 1.1.8

    - name: Install dependencies
      run: bun install

    - name: Run JavaScript/TypeScript tests
      run: bun run test

    - name: Upload coverage to Coveralls
      run: |
        if [ -f ./coverage/lcov.info ]; then
          bun run coveralls < ./coverage/lcov.info
        fi
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install Clippy
      run: rustup component add clippy

    - name: Run Clippy
      run: cargo clippy -- -D warnings
      shell: bash

    - name: Build Rust project
      run: cargo build
      shell: bash

    - name: Run Rust tests
      run: cargo test
      shell: bash
